# This config file defines log retention/rotation policies for curator <= 3.2.1
# Pass it into curator by running:
# $ oc secrets new curator-config settings=curator-config.yaml
# $ oc volumes dc/logging-curator --add --type=secret --secret-name=curator-config --mount-path=/etc/curator --name=curator-config --overwrite
# Make sure curator settings exist when you rsh into curator pod:

    .defaults:
      delete:
        days: 30
      runhour: 4
      runminute: 15
 
    .operations:
      delete:
        days: 1
 
    day1:
      delete:
        days: 1

    day1-dup:
      delete:
        days: 1

    day1-tri:
      delete:
        days: 1
 
    week1:
      delete:
        weeks: 1
 
    month1:
      delete:
        months: 1
